echo "Suppression de l'index 'receipe'..."
curl -X DELETE "localhost:9200/receipe"
echo -e "\n✅ L'index 'receipe' supprimé ✅"
echo "Recréation de l'index 'receipe'..."
curl -X PUT "localhost:9200/receipe"
echo -e "\n✅ L'index 'receipe' recréé ✅\n"

echo "Suppression de l'index 'accounts'..."
curl -X DELETE "localhost:9200/accounts"
echo -e "\n✅ L'index 'accounts' supprimé ✅"
echo "Recréation de l'index 'accounts'..."
curl -X PUT "localhost:9200/accounts"
echo -e "\n✅ L'index 'accounts' recréé ✅\n"

echo "Suppression de l'index 'movies'..."
curl -X DELETE "localhost:9200/movies"
echo -e "\n✅ L'index 'movies' supprimé ✅"
echo "Recréation de l'index 'movies'..."
curl -X PUT "localhost:9200/movies"
echo -e "\n✅ L'index 'movies' recréé ✅\n"

echo "Suppression de l'index 'products'..."
curl -X DELETE "localhost:9200/products"
echo -e "\n✅ L'index 'products' supprimé ✅"
echo "Recréation de l'index 'products'..."
curl -X PUT "localhost:9200/products"
echo -e "\n✅ L'index 'products' recréé ✅\n"

echo "Suppression et recréation terminées pour tous les indices."
